import {
  IArchQuest,
  IInventionAugment,
  IPrayer,
  IRelic,
  ISpell,
  EPrayerBook,
  ESpellBook,
} from './playerinput.model';

export const PRAYERS: IPrayer[] = [
  {
    name: 'ultimatestrength',
    type: 'dmg',
    prayerBook: EPrayerBook.STANDARD,
    style: 'melee',
    level: 46,
    accuracyBoost: 0,
    damageBoost: 0.1,
  },
  {
    name: 'eagleeye',
    type: 'dmg',
    prayerBook: EPrayerBook.STANDARD,
    style: 'ranged',
    level: 44,
    accuracyBoost: 0,
    damageBoost: 0.1,
  },
  {
    name: 'mysticmight',
    type: 'dmg',
    prayerBook: EPrayerBook.STANDARD,
    style: 'magic',
    level: 45,
    accuracyBoost: 0,
    damageBoost: 0.1,
  },
  {
    name: 'accelerateddecay',
    type: 'dmg',
    prayerBook: EPrayerBook.STANDARD,
    style: 'necromancy',
    level: 43,
    accuracyBoost: 0,
    damageBoost: 0.1,
  },
  {
    name: 'eclipsedsoul',
    type: 'dmg',
    prayerBook: EPrayerBook.STANDARD,
    style: 'necromancy',
    level: 66,
    accuracyBoost: 0,
    damageBoost: 0.15,
  },
  {
    name: 'piety',
    type: 'dmg',
    prayerBook: EPrayerBook.STANDARD,
    style: 'melee',
    level: 70,
    accuracyBoost: 0,
    damageBoost: 0.15,
  },
  {
    name: 'rigour',
    type: 'dmg',
    prayerBook: EPrayerBook.STANDARD,
    style: 'ranged',
    level: 74,
    accuracyBoost: 0,
    damageBoost: 0.15,
  },
  {
    name: 'augury',
    type: 'dmg',
    prayerBook: EPrayerBook.STANDARD,
    style: 'magic',
    level: 77,
    accuracyBoost: 0,
    damageBoost: 0.15,
  },
  {
    name: 'sanctity',
    type: 'dmg',
    prayerBook: EPrayerBook.STANDARD,
    style: 'necromancy',
    level: 71,
    accuracyBoost: 0,
    damageBoost: 0.2,
  },
  {
    name: 'divinerage',
    type: 'dmg',
    prayerBook: EPrayerBook.STANDARD,
    style: 'all',
    level: 85,
    accuracyBoost: 0,
    damageBoost: 0.05,
  },
  {
    name: 'turmoil',
    type: 'dmg',
    prayerBook: EPrayerBook.CURSES,
    style: 'melee',
    level: 95,
    accuracyBoost: 0,
    damageBoost: 0.1,
  },
  {
    name: 'torment',
    type: 'dmg',
    prayerBook: EPrayerBook.CURSES,
    style: 'magic',
    level: 95,
    accuracyBoost: 0,
    damageBoost: 0.1,
  },
  {
    name: 'anguish',
    type: 'dmg',
    prayerBook: EPrayerBook.CURSES,
    style: 'ranged',
    level: 95,
    accuracyBoost: 0,
    damageBoost: 0.1,
  },
  {
    name: 'sorrow',
    type: 'dmg',
    prayerBook: EPrayerBook.CURSES,
    style: 'necromancy',
    level: 95,
    accuracyBoost: 0,
    damageBoost: 0.1,
  },
  {
    name: 'soulsplit',
    type: 'overhead',
    prayerBook: EPrayerBook.CURSES,
    style: 'all',
    level: 92,
    accuracyBoost: 0,
    damageBoost: 0,
  },
  {
    name: 'malevolence',
    type: 'dmg',
    prayerBook: EPrayerBook.CURSES,
    style: 'melee',
    level: 99,
    accuracyBoost: 0.02,
    damageBoost: 0.12,
  },
  {
    name: 'affliction',
    type: 'dmg',
    prayerBook: EPrayerBook.CURSES,
    style: 'magic',
    level: 99,
    accuracyBoost: 0.02,
    damageBoost: 0.12,
  },
  {
    name: 'desolation',
    type: 'dmg',
    prayerBook: EPrayerBook.CURSES,
    style: 'ranged',
    level: 99,
    accuracyBoost: 0.02,
    damageBoost: 0.12,
  },
  {
    name: 'ruination',
    type: 'dmg',
    prayerBook: EPrayerBook.CURSES,
    style: 'necromancy',
    level: 99,
    accuracyBoost: 0.02,
    damageBoost: 0.12,
  },
  {
    name: 'splitsoul',
    type: 'overhead',
    prayerBook: EPrayerBook.CURSES,
    style: 'necromancy',
    level: 92,
    accuracyBoost: 0,
    damageBoost: 0,
  },
];

export const SPELLS: ISpell[] = [
  { name: 'airsurge', spellBook: ESpellBook.STANDARD },
  { name: 'watersurge', spellBook: ESpellBook.STANDARD },
  { name: 'earthsurge', spellBook: ESpellBook.STANDARD },
  { name: 'firesurge', spellBook: ESpellBook.STANDARD },
  { name: 'crumbleundead', spellBook: ESpellBook.STANDARD },
  { name: 'smokebarrage', spellBook: ESpellBook.ANCIENT },
  { name: 'shadowbarrage', spellBook: ESpellBook.ANCIENT },
  { name: 'bloodbarrage', spellBook: ESpellBook.ANCIENT },
  { name: 'icebarrage', spellBook: ESpellBook.ANCIENT },
  { name: 'exsanguinate', spellBook: ESpellBook.ANCIENT },
  { name: 'opalaurora', spellBook: ESpellBook.ANCIENT },
  { name: 'sapphireaurora', spellBook: ESpellBook.ANCIENT },
  { name: 'emeraldaurora', spellBook: ESpellBook.ANCIENT },
  { name: 'rubyaurora', spellBook: ESpellBook.ANCIENT },
  { name: 'incitefear', spellBook: ESpellBook.ANCIENT },
];

export const INVENTION_AUGMENTS: IInventionAugment[] = [
  {
    name: 'Mainhand Weapon',
    icon: 'mainhand',
    perkSlots: [
      {
        name: 'Perk 1',
        selectedPerk: null,
        options: [],
        occupiedByAdjacent: false,
      },
    ],
    longPartOptions: [],
    activeLongPart: 'None',
  },
  {
    name: 'Offhand Weapon',
    icon: 'offhand',
    perkSlots: [
      {
        name: 'Perk 1',
        selectedPerk: null,
        options: [],
        occupiedByAdjacent: false,
      },
    ],
    longPartOptions: [],
    activeLongPart: 'None',
  },
  {
    name: 'Two-Handed Weapon',
    icon: 'twohand',
    perkSlots: [
      {
        name: 'Perk 1',
        selectedPerk: null,
        options: [],
        occupiedByAdjacent: false,
      },
      {
        name: 'Perk 2',
        selectedPerk: null,
        options: [],
        occupiedByAdjacent: false,
      },
    ],
    longPartOptions: [],
    activeLongPart: 'None',
  },
  {
    name: 'Body Armour',
    icon: 'chest',
    perkSlots: [
      {
        name: 'Perk 1',
        selectedPerk: null,
        options: [],
        occupiedByAdjacent: false,
      },
      {
        name: 'Perk 2',
        selectedPerk: null,
        options: [],
        occupiedByAdjacent: false,
      },
    ],
    longPartOptions: [],
    activeLongPart: 'None',
  },
  {
    name: 'Leg Armour',
    icon: 'legs',
    perkSlots: [
      {
        name: 'Perk 1',
        selectedPerk: null,
        options: [],
        occupiedByAdjacent: false,
      },
      {
        name: 'Perk 2',
        selectedPerk: null,
        options: [],
        occupiedByAdjacent: false,
      },
    ],
    longPartOptions: [],
    activeLongPart: 'None',
  },
];

export const ARCH_QUESTS: IArchQuest[] = [
  { name: 'None', limit: 150, unlocked: true },
  { name: 'Archaeology tutorial', limit: 150, unlocked: true },
  { name: 'Existence', limit: 250, unlocked: true },
  { name: 'Architecture', limit: 400, unlocked: true },
  { name: 'Symbology', limit: 500, unlocked: true },
  { name: 'Mysterious City', limit: 650, unlocked: true },
];

export const ARCH_RELICS: IRelic[] = [
  { name: 'Font of Life', cost: 100, equipped: false, icon: 'fontoflife' },
  { name: "Berserker's Fury", cost: 200, equipped: false, icon: 'berserkerfury' },
  { name: "Shadow's Grace", cost: 150, equipped: false, icon: 'shadowgrace' },
  { name: 'Blessing of Het', cost: 300, equipped: false, icon: 'blessingofhet' },
  { name: 'Death Ward', cost: 250, equipped: false, icon: 'deathward' },
  { name: 'Fury of the Small', cost: 200, equipped: false, icon: 'furyofthesmall' },
  { name: 'Persistent Rage', cost: 250, equipped: false, icon: 'persistentrage' },
  { name: 'Heightened Senses', cost: 300, equipped: false, icon: 'heightenedsenses' },
  { name: 'Conservation of Energy', cost: 400, equipped: false, icon: 'conservationofenergy' },
];
